article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"
urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<str:title>',views.detail,name = "detail"),
    path('update/<str:title>',views.updateArticle,name = "update"),
    path('delete/<str:title>',views.deleteArticle,name = "delete"),
    path('/blog',views.blog,name = "blog"),
    path('/comment/<str:title>',views.addComment,name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("home.urls")),
    path('blog/',views.blog,name="blog"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/addarticle.html
{% extends "leyaut.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "inculudes/navbar.html" %}

<div class="row" style="margin-top:100px;">
    <div class="col-md-6 offset-md-3">
        <h3>Kontrol Paneli/<small>Makale Ekleme</small></h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form.media}}
            
           {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Ekle</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/blog.html
{% extends "leyaut.html" %}
{% block body %}
{% include "inculudes/navbar.html" %}
<div class="container">

<h3>Hakkımızda</h3>
<br>
<hr>
<div class="row">
<div class="col-md-8">
{% if articles %}
{% for article in articles %}
<div class="card" style="width: 18rem;">
{% if article.article_image %}
        <img class="card-img-top" src="{{article.article_image.url}}" alt="">
    {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text">{{article.content|safe|truncatewords:5}}</p>
    <a href="{% url 'article:detail' article.title %}" class="btn btn-primary">Daha Fazlası</a>
  </div>
</div>
{% endfor %}
{% else %}
<div class="alert alert-danger">Makale Bulunamadı</div>
{% endif %}
</div>
<div class="col-md-4">
</div>
</div>

</div>


{% endblock body %}

templates/dashboard.html
{% extends "leyaut.html" %}
{% block body %}
{% include "inculudes/navbar.html" %}
<div class="container">
<h3>Kontrol Paneli</h3>
<hr>
<p>Hoşgeldiniz,<small>{{request.user.username}}</small></p>
<hr>
<a href="{% url 'article:addarticle' %}" class="btn btn-danger">Makale Ekle</a>
<hr>
{% if articles  %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="{% url 'article:detail' article.title %}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href="{% url 'article:update' article.title %}" class="btn btn-success">Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.title %}" class="btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}
    
  </tbody>
</table>
{% else %}
<div class="alert alert-danger">Makale Bulunamadı</div>
{% endif %}

</div>
{% endblock body %}

templates/detail.html
{% extends "leyaut.html" %}
{% block body %}
{% include "inculudes/navbar.html" %}
<div class="container">
<div class="card text-left">
  <div class="card-header text-center">
    BY {{article.author}} 
  </div>
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text">{{article.content|safe}}</p>
  </div>
  <div class="card-footer text-muted text-center">
    {{article.created_date}}
  </div>
</div>
<br>
<h5>Yorumlar</h5>
{% if comments %}

{% for comment in comments %}
<div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_content}}
            <br>
            <small style="color:grey;">{{comment.comment_date}}</small>
          </div>
        </div>
{% endfor %}
{% else %}
<div class="alert alert-danger">Henüz Yorum Yapılmamış</div>
{% endif %}

        <div class="card my-4">
          <h5 class="card-header">Yorum Ekle</h5>
          <div class="card-body">
          
            <form method="post" action="{% url 'article:comment' article.id %}">
            {% csrf_token %}
              <div class="form-group">
              <label for="exampleFormControlInput1">İsminiz</label>
               <input name = "comment_author" class="form-control"  placeholder="isminiz">
              </div>
              <div class="form-group">
              <label for="exampleFormControlInput1">İçerik</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Ekle</button>
            </form>
          </div>
        </div>
</div>
{% endblock body %}

templates/leyaut.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
    <title>Rıdvan Cindioğlu</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/c8d7d5cd5d.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

</head>

<body>
    <br><br><br>
    <div class="container">
    {% if messages %}
            {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
            
            {% endfor %}
    {% endif %}
    </div>

    {% block body %}
    
    {% endblock body %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script>
        $(window).scroll(function () {
            if ($(document).scrollTop() > 100) {
                $('.navbar').addClass('color-change');
            } else {
                $('.navbar').removeClass('color-change');
            }
        });

    </script>
    <script>
        var scroll = new SmoothScroll('a[href*="#"]');
    </script>
    


</body>

</html>

templates/login.html
{% extends "leyaut.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "inculudes/navbar.html" %}
<br><br><br>
<div class="row" style="margin-top:100px;">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
           {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/logout.html
{% extends "leyaut.html" %}

{% block body %}
{% include "inculudes/navbar.html" %}
<h3>Çıkış Yap</h3>
{% endblock body %}

templates/register.html
{% extends "leyaut.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "inculudes/navbar.html" %}


<div class="row" style="margin-top:100px;">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
           {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
  </div>

{% endblock body %}

templates/update.html
{% extends "leyaut.html" %}
{% load crispy_forms_tags %}
{% block body %}
{% include "inculudes/navbar.html" %}

<div class="" style="margin-top:100px;">
    <div class="col-md-6 offset-md-3">
        <h3>Kontrol Paneli/<small>Makale Güncelleme</small></h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            {{form.media}}
            
           {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>
        </form>
    </div>
  </div>

{% endblock body %}